# RuboCop reference
# @see: https://docs.rubocop.org/rubocop/cops.html
# @see: https://docs.rubocop.org/rubocop-capybara/cops.html
# @see: https://docs.rubocop.org/rubocop-minitest/cops.html
# @see: https://docs.rubocop.org/rubocop-performance/cops.html
# @see: https://docs.rubocop.org/rubocop-rails/cops.html

require:
  - rubocop-capybara
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake

AllCops:
  Exclude:
    - db/schema.rb
  NewCops: enable

Layout/LineLength:
  Max: 120

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - db/migrate/*

Metrics/BlockLength:
  Exclude:
    - config/environments/*
  Enabled: true

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Performance/AncestorsInclude:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - development
    - test

Rails/EnvironmentVariableAccess:
  Enabled: false

Style/ArrayCoercion:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
